;; Generated by :claw at 1956-08-02T07:55:37.000000Z
(uiop:define-package :%gdextension (:use))
(uiop:define-package :aw-gdextension-spec-bindings~pristine (:use :cl))
(common-lisp:in-package :aw-gdextension-spec-bindings~pristine)

(defparameter %gdextension::+interface-h+ nil)

(cffi:defcenum
 (%gdextension::call-error-type-enum :unsigned-int)
 "/Users/jason/common-lisp/aw-gdextension/include/gdextension_interface.h:183:9"
 (:ok 0)
 (:error-invalid-method 1)
 (:error-invalid-argument 2)
 (:error-too-many-arguments 3)
 (:error-too-few-arguments 4)
 (:error-instance-is-null 5)
 (:error-method-not-const 6))

(cffi:defcenum
 (%gdextension::class-method-argument-metadata-enum
  :unsigned-int)
 "/Users/jason/common-lisp/aw-gdextension/include/gdextension_interface.h:416:9"
 (:none 0)
 (:int-is-int8 1)
 (:int-is-int16 2)
 (:int-is-int32 3)
 (:int-is-int64 4)
 (:int-is-uint8 5)
 (:int-is-uint16 6)
 (:int-is-uint32 7)
 (:int-is-uint64 8)
 (:real-is-float 9)
 (:real-is-double 10)
 (:int-is-char16 11)
 (:int-is-char32 12))

(cffi:defbitfield
 (%gdextension::class-method-flags-enum :unsigned-int)
 "/Users/jason/common-lisp/aw-gdextension/include/gdextension_interface.h:406:9"
 (:flag-normal 1)
 (:flag-editor 2)
 (:flag-const 4)
 (:flag-virtual 8)
 (:flag-vararg 16)
 (:flag-static 32)
 (:flags-default 1))

(cffi:defcenum
 (%gdextension::initialization-level-enum :unsigned-int)
 "/Users/jason/common-lisp/aw-gdextension/include/gdextension_interface.h:726:9"
 (:initialization-core 0)
 (:initialization-servers 1)
 (:initialization-scene 2)
 (:initialization-editor 3)
 (:max-initialization-level 4))

(cffi:defcenum
 (%gdextension::variant-operator-enum :unsigned-int)
 "/Users/jason/common-lisp/aw-gdextension/include/gdextension_interface.h:104:9"
 (:equal 0)
 (:not-equal 1)
 (:less 2)
 (:less-equal 3)
 (:greater 4)
 (:greater-equal 5)
 (:add 6)
 (:subtract 7)
 (:multiply 8)
 (:divide 9)
 (:negate 10)
 (:positive 11)
 (:module 12)
 (:power 13)
 (:shift-left 14)
 (:shift-right 15)
 (:bit-and 16)
 (:bit-or 17)
 (:bit-xor 18)
 (:bit-negate 19)
 (:and 20)
 (:or 21)
 (:xor 22)
 (:not 23)
 (:in 24)
 (:max 25))

(cffi:defcenum (%gdextension::variant-type-enum :unsigned-int)
               "/Users/jason/common-lisp/aw-gdextension/include/gdextension_interface.h:52:9"
               (:nil 0)
               (:bool 1)
               (:int 2)
               (:float 3)
               (:string 4)
               (:vector2 5)
               (:vector2i 6)
               (:rect2 7)
               (:rect2i 8)
               (:vector3 9)
               (:vector3i 10)
               (:transform2d 11)
               (:vector4 12)
               (:vector4i 13)
               (:plane 14)
               (:quaternion 15)
               (:aabb 16)
               (:basis 17)
               (:transform3d 18)
               (:projection 19)
               (:color 20)
               (:string-name 21)
               (:node-path 22)
               (:rid 23)
               (:object 24)
               (:callable 25)
               (:signal 26)
               (:dictionary 27)
               (:array 28)
               (:packed-byte-array 29)
               (:packed-int32-array 30)
               (:packed-int64-array 31)
               (:packed-float32-array 32)
               (:packed-float64-array 33)
               (:packed-string-array 34)
               (:packed-vector2-array 35)
               (:packed-vector3-array 36)
               (:packed-color-array 37)
               (:packed-vector4-array 38)
               (:variant-max 39))

(cffi:defctype %gdextension::call-error-type
               %gdextension::call-error-type-enum)

(cffi:defctype %gdextension::int32-t :int)

(cffi:defcstruct (%gdextension::call-error-struct :size 12)
                 (%gdextension::error-arg %gdextension::call-error-type :offset 0)
                 (%gdextension::argument %gdextension::int32-t :offset 4)
                 (%gdextension::expected %gdextension::int32-t :offset 8))

(cffi:defctype %gdextension::gd-object-instance-id :unsigned-long-long)

(cffi:defctype %gdextension::callable-custom-call (:pointer :void))

(cffi:defctype %gdextension::callable-custom-is-valid (:pointer :void))

(cffi:defctype %gdextension::callable-custom-free (:pointer :void))

(cffi:defctype %gdextension::callable-custom-hash (:pointer :void))

(cffi:defctype %gdextension::callable-custom-equal (:pointer :void))

(cffi:defctype %gdextension::callable-custom-less-than (:pointer :void))

(cffi:defctype %gdextension::callable-custom-to-string (:pointer :void))

(cffi:defcstruct
 (%gdextension::callable-custom-info-struct :size 80)
 (%gdextension::callable-userdata (:pointer :void) :offset 0)
 (%gdextension::token (:pointer :void) :offset 8)
 (%gdextension::object-id %gdextension::gd-object-instance-id :offset 16)
 (%gdextension::call-func %gdextension::callable-custom-call :offset 24)
 (%gdextension::is-valid-func %gdextension::callable-custom-is-valid :offset
  32)
 (%gdextension::free-func %gdextension::callable-custom-free :offset 40)
 (%gdextension::hash-func %gdextension::callable-custom-hash :offset 48)
 (%gdextension::equal-func %gdextension::callable-custom-equal :offset 56)
 (%gdextension::less-than-func %gdextension::callable-custom-less-than :offset
  64)
 (%gdextension::to-string-func %gdextension::callable-custom-to-string :offset
  72))

(cffi:defctype %gdextension::callable-custom-get-argument-count
               (:pointer :void))

(cffi:defcstruct
 (%gdextension::callable-custom-info2-struct :size 88)
 (%gdextension::callable-userdata (:pointer :void) :offset 0)
 (%gdextension::token (:pointer :void) :offset 8)
 (%gdextension::object-id %gdextension::gd-object-instance-id :offset 16)
 (%gdextension::call-func %gdextension::callable-custom-call :offset 24)
 (%gdextension::is-valid-func %gdextension::callable-custom-is-valid :offset
  32)
 (%gdextension::free-func %gdextension::callable-custom-free :offset 40)
 (%gdextension::hash-func %gdextension::callable-custom-hash :offset 48)
 (%gdextension::equal-func %gdextension::callable-custom-equal :offset 56)
 (%gdextension::less-than-func %gdextension::callable-custom-less-than :offset
  64)
 (%gdextension::to-string-func %gdextension::callable-custom-to-string :offset
  72)
 (%gdextension::get-argument-count-func
  %gdextension::callable-custom-get-argument-count :offset 80))

(cffi:defctype %gdextension::bool :unsigned-char)

(cffi:defctype %gdextension::class-set (:pointer :void))

(cffi:defctype %gdextension::class-get (:pointer :void))

(cffi:defctype %gdextension::class-get-property-list (:pointer :void))

(cffi:defctype %gdextension::class-free-property-list (:pointer :void))

(cffi:defctype %gdextension::class-property-can-revert (:pointer :void))

(cffi:defctype %gdextension::class-property-get-revert (:pointer :void))

(cffi:defctype %gdextension::class-notification (:pointer :void))

(cffi:defctype %gdextension::class-to-string (:pointer :void))

(cffi:defctype %gdextension::class-reference (:pointer :void))

(cffi:defctype %gdextension::class-unreference (:pointer :void))

(cffi:defctype %gdextension::class-create-instance (:pointer :void))

(cffi:defctype %gdextension::class-free-instance (:pointer :void))

(cffi:defctype %gdextension::class-get-virtual (:pointer :void))

(cffi:defctype %gdextension::class-get-rid (:pointer :void))

(cffi:defcstruct
 (%gdextension::class-creation-info-struct :size 128)
 (%gdextension::is-virtual %gdextension::bool :offset 0)
 (%gdextension::is-abstract %gdextension::bool :offset 1)
 (%gdextension::set-func %gdextension::class-set :offset 8)
 (%gdextension::get-func %gdextension::class-get :offset 16)
 (%gdextension::get-property-list-func %gdextension::class-get-property-list
  :offset 24)
 (%gdextension::free-property-list-func %gdextension::class-free-property-list
  :offset 32)
 (%gdextension::property-can-revert-func
  %gdextension::class-property-can-revert :offset 40)
 (%gdextension::property-get-revert-func
  %gdextension::class-property-get-revert :offset 48)
 (%gdextension::notification-func %gdextension::class-notification :offset 56)
 (%gdextension::to-string-func %gdextension::class-to-string :offset 64)
 (%gdextension::reference-func %gdextension::class-reference :offset 72)
 (%gdextension::unreference-func %gdextension::class-unreference :offset 80)
 (%gdextension::create-instance-func %gdextension::class-create-instance
  :offset 88)
 (%gdextension::free-instance-func %gdextension::class-free-instance :offset
  96)
 (%gdextension::get-virtual-func %gdextension::class-get-virtual :offset 104)
 (%gdextension::get-rid-func %gdextension::class-get-rid :offset 112)
 (%gdextension::class-userdata (:pointer :void) :offset 120))

(cffi:defctype %gdextension::class-validate-property (:pointer :void))

(cffi:defctype %gdextension::class-notification2 (:pointer :void))

(cffi:defctype %gdextension::class-recreate-instance (:pointer :void))

(cffi:defctype %gdextension::class-get-virtual-call-data (:pointer :void))

(cffi:defctype %gdextension::class-call-virtual-with-data (:pointer :void))

(cffi:defcstruct
 (%gdextension::class-creation-info2-struct :size 160)
 (%gdextension::is-virtual %gdextension::bool :offset 0)
 (%gdextension::is-abstract %gdextension::bool :offset 1)
 (%gdextension::is-exposed %gdextension::bool :offset 2)
 (%gdextension::set-func %gdextension::class-set :offset 8)
 (%gdextension::get-func %gdextension::class-get :offset 16)
 (%gdextension::get-property-list-func %gdextension::class-get-property-list
  :offset 24)
 (%gdextension::free-property-list-func %gdextension::class-free-property-list
  :offset 32)
 (%gdextension::property-can-revert-func
  %gdextension::class-property-can-revert :offset 40)
 (%gdextension::property-get-revert-func
  %gdextension::class-property-get-revert :offset 48)
 (%gdextension::validate-property-func %gdextension::class-validate-property
  :offset 56)
 (%gdextension::notification-func %gdextension::class-notification2 :offset 64)
 (%gdextension::to-string-func %gdextension::class-to-string :offset 72)
 (%gdextension::reference-func %gdextension::class-reference :offset 80)
 (%gdextension::unreference-func %gdextension::class-unreference :offset 88)
 (%gdextension::create-instance-func %gdextension::class-create-instance
  :offset 96)
 (%gdextension::free-instance-func %gdextension::class-free-instance :offset
  104)
 (%gdextension::recreate-instance-func %gdextension::class-recreate-instance
  :offset 112)
 (%gdextension::get-virtual-func %gdextension::class-get-virtual :offset 120)
 (%gdextension::get-virtual-call-data-func
  %gdextension::class-get-virtual-call-data :offset 128)
 (%gdextension::call-virtual-with-data-func
  %gdextension::class-call-virtual-with-data :offset 136)
 (%gdextension::get-rid-func %gdextension::class-get-rid :offset 144)
 (%gdextension::class-userdata (:pointer :void) :offset 152))

(cffi:defctype %gdextension::class-free-property-list2 (:pointer :void))

(cffi:defcstruct
 (%gdextension::class-creation-info3-struct :size 160)
 (%gdextension::is-virtual %gdextension::bool :offset 0)
 (%gdextension::is-abstract %gdextension::bool :offset 1)
 (%gdextension::is-exposed %gdextension::bool :offset 2)
 (%gdextension::is-runtime %gdextension::bool :offset 3)
 (%gdextension::set-func %gdextension::class-set :offset 8)
 (%gdextension::get-func %gdextension::class-get :offset 16)
 (%gdextension::get-property-list-func %gdextension::class-get-property-list
  :offset 24)
 (%gdextension::free-property-list-func %gdextension::class-free-property-list2
  :offset 32)
 (%gdextension::property-can-revert-func
  %gdextension::class-property-can-revert :offset 40)
 (%gdextension::property-get-revert-func
  %gdextension::class-property-get-revert :offset 48)
 (%gdextension::validate-property-func %gdextension::class-validate-property
  :offset 56)
 (%gdextension::notification-func %gdextension::class-notification2 :offset 64)
 (%gdextension::to-string-func %gdextension::class-to-string :offset 72)
 (%gdextension::reference-func %gdextension::class-reference :offset 80)
 (%gdextension::unreference-func %gdextension::class-unreference :offset 88)
 (%gdextension::create-instance-func %gdextension::class-create-instance
  :offset 96)
 (%gdextension::free-instance-func %gdextension::class-free-instance :offset
  104)
 (%gdextension::recreate-instance-func %gdextension::class-recreate-instance
  :offset 112)
 (%gdextension::get-virtual-func %gdextension::class-get-virtual :offset 120)
 (%gdextension::get-virtual-call-data-func
  %gdextension::class-get-virtual-call-data :offset 128)
 (%gdextension::call-virtual-with-data-func
  %gdextension::class-call-virtual-with-data :offset 136)
 (%gdextension::get-rid-func %gdextension::class-get-rid :offset 144)
 (%gdextension::class-userdata (:pointer :void) :offset 152))

(cffi:defctype %gdextension::const-string-ptr (:pointer :void))

(cffi:defctype %gdextension::class-create-instance2 (:pointer :void))

(cffi:defctype %gdextension::class-get-virtual2 (:pointer :void))

(cffi:defctype %gdextension::class-get-virtual-call-data2 (:pointer :void))

(cffi:defcstruct
 (%gdextension::class-creation-info4-struct :size 160)
 (%gdextension::is-virtual %gdextension::bool :offset 0)
 (%gdextension::is-abstract %gdextension::bool :offset 1)
 (%gdextension::is-exposed %gdextension::bool :offset 2)
 (%gdextension::is-runtime %gdextension::bool :offset 3)
 (%gdextension::icon-path %gdextension::const-string-ptr :offset 8)
 (%gdextension::set-func %gdextension::class-set :offset 16)
 (%gdextension::get-func %gdextension::class-get :offset 24)
 (%gdextension::get-property-list-func %gdextension::class-get-property-list
  :offset 32)
 (%gdextension::free-property-list-func %gdextension::class-free-property-list2
  :offset 40)
 (%gdextension::property-can-revert-func
  %gdextension::class-property-can-revert :offset 48)
 (%gdextension::property-get-revert-func
  %gdextension::class-property-get-revert :offset 56)
 (%gdextension::validate-property-func %gdextension::class-validate-property
  :offset 64)
 (%gdextension::notification-func %gdextension::class-notification2 :offset 72)
 (%gdextension::to-string-func %gdextension::class-to-string :offset 80)
 (%gdextension::reference-func %gdextension::class-reference :offset 88)
 (%gdextension::unreference-func %gdextension::class-unreference :offset 96)
 (%gdextension::create-instance-func %gdextension::class-create-instance2
  :offset 104)
 (%gdextension::free-instance-func %gdextension::class-free-instance :offset
  112)
 (%gdextension::recreate-instance-func %gdextension::class-recreate-instance
  :offset 120)
 (%gdextension::get-virtual-func %gdextension::class-get-virtual2 :offset 128)
 (%gdextension::get-virtual-call-data-func
  %gdextension::class-get-virtual-call-data2 :offset 136)
 (%gdextension::call-virtual-with-data-func
  %gdextension::class-call-virtual-with-data :offset 144)
 (%gdextension::class-userdata (:pointer :void) :offset 152))

(cffi:defctype %gdextension::string-name-ptr (:pointer :void))

(cffi:defctype %gdextension::class-method-call (:pointer :void))

(cffi:defctype %gdextension::class-method-ptr-call (:pointer :void))

(cffi:defctype %gdextension::variant-type
               %gdextension::variant-type-enum)

(cffi:defctype %gdextension::string-ptr (:pointer :void))

(cffi:defctype %gdextension::uint32-t :unsigned-int)

(cffi:defcstruct (%gdextension::property-info-struct :size 48)
                 (%gdextension::type %gdextension::variant-type :offset 0)
                 (%gdextension::name %gdextension::string-name-ptr :offset 8)
                 (%gdextension::class-name %gdextension::string-name-ptr
                  :offset 16)
                 (%gdextension::hint %gdextension::uint32-t :offset 24)
                 (%gdextension::hint-string %gdextension::string-ptr :offset
                  32)
                 (%gdextension::usage %gdextension::uint32-t :offset 40))

(cffi:defctype %gdextension::property-info
               (:struct %gdextension::property-info-struct))

(cffi:defctype %gdextension::class-method-argument-metadata
               %gdextension::class-method-argument-metadata-enum)

(cffi:defctype %gdextension::variant-ptr (:pointer :void))

(cffi:defcstruct
 (%gdextension::class-method-info-struct :size 88)
 (%gdextension::name %gdextension::string-name-ptr :offset 0)
 (%gdextension::method-userdata (:pointer :void) :offset 8)
 (%gdextension::call-func %gdextension::class-method-call :offset 16)
 (%gdextension::ptrcall-func %gdextension::class-method-ptr-call :offset 24)
 (%gdextension::method-flags %gdextension::uint32-t :offset 32)
 (%gdextension::has-return-value %gdextension::bool :offset 36)
 (%gdextension::return-value-info (:pointer %gdextension::property-info)
  :offset 40)
 (%gdextension::return-value-metadata
  %gdextension::class-method-argument-metadata :offset 48)
 (%gdextension::argument-count %gdextension::uint32-t :offset 52)
 (%gdextension::arguments-info (:pointer %gdextension::property-info) :offset
  56)
 (%gdextension::arguments-metadata
  (:pointer %gdextension::class-method-argument-metadata) :offset 64)
 (%gdextension::default-argument-count %gdextension::uint32-t :offset 72)
 (%gdextension::default-arguments (:pointer %gdextension::variant-ptr) :offset
  80))

(cffi:defcstruct
 (%gdextension::class-virtual-method-info-struct :size 88)
 (%gdextension::name %gdextension::string-name-ptr :offset 0)
 (%gdextension::method-flags %gdextension::uint32-t :offset 8)
 (%gdextension::return-value %gdextension::property-info :offset 16)
 (%gdextension::return-value-metadata
  %gdextension::class-method-argument-metadata :offset 64)
 (%gdextension::argument-count %gdextension::uint32-t :offset 68)
 (%gdextension::arguments (:pointer %gdextension::property-info) :offset 72)
 (%gdextension::arguments-metadata
  (:pointer %gdextension::class-method-argument-metadata) :offset 80))

(cffi:defcstruct (%gdextension::godot-version-struct :size 24)
                 (%gdextension::major %gdextension::uint32-t :offset 0)
                 (%gdextension::minor %gdextension::uint32-t :offset 4)
                 (%gdextension::patch %gdextension::uint32-t :offset 8)
                 (%gdextension::string :string :offset 16))

(cffi:defctype %gdextension::initialization-level
               %gdextension::initialization-level-enum)

(cffi:defcstruct (%gdextension::initialization-struct :size 32)
                 (%gdextension::minimum-initialization-level
                  %gdextension::initialization-level :offset 0)
                 (%gdextension::userdata (:pointer :void) :offset 8)
                 (%gdextension::initialize (:pointer :void) :offset 16)
                 (%gdextension::deinitialize (:pointer :void) :offset 24))

(cffi:defctype %gdextension::instance-binding-create-callback (:pointer :void))

(cffi:defctype %gdextension::instance-binding-free-callback (:pointer :void))

(cffi:defctype %gdextension::instance-binding-reference-callback
               (:pointer :void))

(cffi:defcstruct
 (%gdextension::instance-binding-callbacks-struct :size 24)
 (%gdextension::create-callback %gdextension::instance-binding-create-callback
  :offset 0)
 (%gdextension::free-callback %gdextension::instance-binding-free-callback
  :offset 8)
 (%gdextension::reference-callback
  %gdextension::instance-binding-reference-callback :offset 16))

(cffi:defcstruct (%gdextension::method-info-struct :size 96)
                 (%gdextension::name %gdextension::string-name-ptr :offset 0)
                 (%gdextension::return-value %gdextension::property-info
                  :offset 8)
                 (%gdextension::flags %gdextension::uint32-t :offset 56)
                 (%gdextension::id %gdextension::int32-t :offset 60)
                 (%gdextension::argument-count %gdextension::uint32-t :offset
                  64)
                 (%gdextension::arguments
                  (:pointer %gdextension::property-info) :offset 72)
                 (%gdextension::default-argument-count %gdextension::uint32-t
                  :offset 80)
                 (%gdextension::default-arguments
                  (:pointer %gdextension::variant-ptr) :offset 88))

(cffi:defctype %gdextension::script-instance-get-property-list (:pointer :void))

(cffi:defctype %gdextension::script-instance-free-property-list
               (:pointer :void))

(cffi:defctype %gdextension::script-instance-property-can-revert
               (:pointer :void))

(cffi:defctype %gdextension::script-instance-property-get-revert
               (:pointer :void))

(cffi:defctype %gdextension::script-instance-get-owner (:pointer :void))

(cffi:defctype %gdextension::script-instance-get-property-state
               (:pointer :void))

(cffi:defctype %gdextension::script-instance-get-method-list (:pointer :void))

(cffi:defctype %gdextension::script-instance-free-method-list (:pointer :void))

(cffi:defctype %gdextension::script-instance-get-property-type (:pointer :void))

(cffi:defctype %gdextension::script-instance-has-method (:pointer :void))

(cffi:defctype %gdextension::script-instance-call (:pointer :void))

(cffi:defctype %gdextension::script-instance-notification (:pointer :void))

(cffi:defctype %gdextension::script-instance-to-string (:pointer :void))

(cffi:defctype %gdextension::script-instance-ref-count-incremented
               (:pointer :void))

(cffi:defctype %gdextension::script-instance-ref-count-decremented
               (:pointer :void))

(cffi:defctype %gdextension::script-instance-get-script (:pointer :void))

(cffi:defctype %gdextension::script-instance-is-placeholder (:pointer :void))

(cffi:defctype %gdextension::script-instance-set (:pointer :void))

(cffi:defctype %gdextension::script-instance-get (:pointer :void))

(cffi:defctype %gdextension::script-instance-get-language (:pointer :void))

(cffi:defctype %gdextension::script-instance-free (:pointer :void))

(cffi:defcstruct
 (%gdextension::script-instance-info-struct :size 184)
 (%gdextension::set-func %gdextension::script-instance-set :offset 0)
 (%gdextension::get-func %gdextension::script-instance-get :offset 8)
 (%gdextension::get-property-list-func
  %gdextension::script-instance-get-property-list :offset 16)
 (%gdextension::free-property-list-func
  %gdextension::script-instance-free-property-list :offset 24)
 (%gdextension::property-can-revert-func
  %gdextension::script-instance-property-can-revert :offset 32)
 (%gdextension::property-get-revert-func
  %gdextension::script-instance-property-get-revert :offset 40)
 (%gdextension::get-owner-func %gdextension::script-instance-get-owner :offset
  48)
 (%gdextension::get-property-state-func
  %gdextension::script-instance-get-property-state :offset 56)
 (%gdextension::get-method-list-func
  %gdextension::script-instance-get-method-list :offset 64)
 (%gdextension::free-method-list-func
  %gdextension::script-instance-free-method-list :offset 72)
 (%gdextension::get-property-type-func
  %gdextension::script-instance-get-property-type :offset 80)
 (%gdextension::has-method-func %gdextension::script-instance-has-method
  :offset 88)
 (%gdextension::call-func %gdextension::script-instance-call :offset 96)
 (%gdextension::notification-func %gdextension::script-instance-notification
  :offset 104)
 (%gdextension::to-string-func %gdextension::script-instance-to-string :offset
  112)
 (%gdextension::refcount-incremented-func
  %gdextension::script-instance-ref-count-incremented :offset 120)
 (%gdextension::refcount-decremented-func
  %gdextension::script-instance-ref-count-decremented :offset 128)
 (%gdextension::get-script-func %gdextension::script-instance-get-script
  :offset 136)
 (%gdextension::is-placeholder-func
  %gdextension::script-instance-is-placeholder :offset 144)
 (%gdextension::set-fallback-func %gdextension::script-instance-set :offset
  152)
 (%gdextension::get-fallback-func %gdextension::script-instance-get :offset
  160)
 (%gdextension::get-language-func %gdextension::script-instance-get-language
  :offset 168)
 (%gdextension::free-func %gdextension::script-instance-free :offset 176))

(cffi:defctype %gdextension::script-instance-get-class-category
               (:pointer :void))

(cffi:defctype %gdextension::script-instance-validate-property (:pointer :void))

(cffi:defctype %gdextension::script-instance-notification2 (:pointer :void))

(cffi:defcstruct
 (%gdextension::script-instance-info2-struct :size 200)
 (%gdextension::set-func %gdextension::script-instance-set :offset 0)
 (%gdextension::get-func %gdextension::script-instance-get :offset 8)
 (%gdextension::get-property-list-func
  %gdextension::script-instance-get-property-list :offset 16)
 (%gdextension::free-property-list-func
  %gdextension::script-instance-free-property-list :offset 24)
 (%gdextension::get-class-category-func
  %gdextension::script-instance-get-class-category :offset 32)
 (%gdextension::property-can-revert-func
  %gdextension::script-instance-property-can-revert :offset 40)
 (%gdextension::property-get-revert-func
  %gdextension::script-instance-property-get-revert :offset 48)
 (%gdextension::get-owner-func %gdextension::script-instance-get-owner :offset
  56)
 (%gdextension::get-property-state-func
  %gdextension::script-instance-get-property-state :offset 64)
 (%gdextension::get-method-list-func
  %gdextension::script-instance-get-method-list :offset 72)
 (%gdextension::free-method-list-func
  %gdextension::script-instance-free-method-list :offset 80)
 (%gdextension::get-property-type-func
  %gdextension::script-instance-get-property-type :offset 88)
 (%gdextension::validate-property-func
  %gdextension::script-instance-validate-property :offset 96)
 (%gdextension::has-method-func %gdextension::script-instance-has-method
  :offset 104)
 (%gdextension::call-func %gdextension::script-instance-call :offset 112)
 (%gdextension::notification-func %gdextension::script-instance-notification2
  :offset 120)
 (%gdextension::to-string-func %gdextension::script-instance-to-string :offset
  128)
 (%gdextension::refcount-incremented-func
  %gdextension::script-instance-ref-count-incremented :offset 136)
 (%gdextension::refcount-decremented-func
  %gdextension::script-instance-ref-count-decremented :offset 144)
 (%gdextension::get-script-func %gdextension::script-instance-get-script
  :offset 152)
 (%gdextension::is-placeholder-func
  %gdextension::script-instance-is-placeholder :offset 160)
 (%gdextension::set-fallback-func %gdextension::script-instance-set :offset
  168)
 (%gdextension::get-fallback-func %gdextension::script-instance-get :offset
  176)
 (%gdextension::get-language-func %gdextension::script-instance-get-language
  :offset 184)
 (%gdextension::free-func %gdextension::script-instance-free :offset 192))

(cffi:defctype %gdextension::script-instance-free-property-list2
               (:pointer :void))

(cffi:defctype %gdextension::script-instance-free-method-list2 (:pointer :void))

(cffi:defctype %gdextension::script-instance-get-method-argument-count
               (:pointer :void))

(cffi:defcstruct
 (%gdextension::script-instance-info3-struct :size 208)
 (%gdextension::set-func %gdextension::script-instance-set :offset 0)
 (%gdextension::get-func %gdextension::script-instance-get :offset 8)
 (%gdextension::get-property-list-func
  %gdextension::script-instance-get-property-list :offset 16)
 (%gdextension::free-property-list-func
  %gdextension::script-instance-free-property-list2 :offset 24)
 (%gdextension::get-class-category-func
  %gdextension::script-instance-get-class-category :offset 32)
 (%gdextension::property-can-revert-func
  %gdextension::script-instance-property-can-revert :offset 40)
 (%gdextension::property-get-revert-func
  %gdextension::script-instance-property-get-revert :offset 48)
 (%gdextension::get-owner-func %gdextension::script-instance-get-owner :offset
  56)
 (%gdextension::get-property-state-func
  %gdextension::script-instance-get-property-state :offset 64)
 (%gdextension::get-method-list-func
  %gdextension::script-instance-get-method-list :offset 72)
 (%gdextension::free-method-list-func
  %gdextension::script-instance-free-method-list2 :offset 80)
 (%gdextension::get-property-type-func
  %gdextension::script-instance-get-property-type :offset 88)
 (%gdextension::validate-property-func
  %gdextension::script-instance-validate-property :offset 96)
 (%gdextension::has-method-func %gdextension::script-instance-has-method
  :offset 104)
 (%gdextension::get-method-argument-count-func
  %gdextension::script-instance-get-method-argument-count :offset 112)
 (%gdextension::call-func %gdextension::script-instance-call :offset 120)
 (%gdextension::notification-func %gdextension::script-instance-notification2
  :offset 128)
 (%gdextension::to-string-func %gdextension::script-instance-to-string :offset
  136)
 (%gdextension::refcount-incremented-func
  %gdextension::script-instance-ref-count-incremented :offset 144)
 (%gdextension::refcount-decremented-func
  %gdextension::script-instance-ref-count-decremented :offset 152)
 (%gdextension::get-script-func %gdextension::script-instance-get-script
  :offset 160)
 (%gdextension::is-placeholder-func
  %gdextension::script-instance-is-placeholder :offset 168)
 (%gdextension::set-fallback-func %gdextension::script-instance-set :offset
  176)
 (%gdextension::get-fallback-func %gdextension::script-instance-get :offset
  184)
 (%gdextension::get-language-func %gdextension::script-instance-get-language
  :offset 192)
 (%gdextension::free-func %gdextension::script-instance-free :offset 200))

(cffi:defctype %gdextension::call-error
               (:struct %gdextension::call-error-struct))

(cffi:defctype %gdextension::callable-custom-info
               (:struct
                %gdextension::callable-custom-info-struct))

(cffi:defctype %gdextension::callable-custom-info2
               (:struct
                %gdextension::callable-custom-info2-struct))

(cffi:defctype %gdextension::class-creation-info
               (:struct %gdextension::class-creation-info-struct))

(cffi:defctype %gdextension::class-creation-info2
               (:struct
                %gdextension::class-creation-info2-struct))

(cffi:defctype %gdextension::class-creation-info3
               (:struct
                %gdextension::class-creation-info3-struct))

(cffi:defctype %gdextension::class-creation-info4
               (:struct
                %gdextension::class-creation-info4-struct))

(cffi:defctype %gdextension::class-method-flags
               %gdextension::class-method-flags-enum)

(cffi:defctype %gdextension::class-method-info
               (:struct %gdextension::class-method-info-struct))

(cffi:defctype %gdextension::class-virtual-method-info
               (:struct
                %gdextension::class-virtual-method-info-struct))

(cffi:defctype %gdextension::godot-version
               (:struct %gdextension::godot-version-struct))

(cffi:defctype %gdextension::initialization
               (:struct %gdextension::initialization-struct))

(cffi:defctype %gdextension::instance-binding-callbacks
               (:struct
                %gdextension::instance-binding-callbacks-struct))

(cffi:defctype %gdextension::method-info
               (:struct %gdextension::method-info-struct))

(cffi:defctype %gdextension::script-instance-info
               (:struct
                %gdextension::script-instance-info-struct))

(cffi:defctype %gdextension::script-instance-info2
               (:struct
                %gdextension::script-instance-info2-struct))

(cffi:defctype %gdextension::script-instance-info3
               (:struct
                %gdextension::script-instance-info3-struct))

(cffi:defctype %gdextension::variant-operator
               %gdextension::variant-operator-enum)

(cffi:defctype %gdextension::class-call-virtual (:pointer :void))

(cffi:defctype %gdextension::class-instance-ptr (:pointer :void))

(cffi:defctype %gdextension::class-library-ptr (:pointer :void))

(cffi:defctype %gdextension::class-method-validated-call (:pointer :void))

(cffi:defctype %gdextension::const-object-ptr (:pointer :void))

(cffi:defctype %gdextension::const-ref-ptr (:pointer :void))

(cffi:defctype %gdextension::const-string-name-ptr (:pointer :void))

(cffi:defctype %gdextension::const-type-ptr (:pointer :void))

(cffi:defctype %gdextension::const-variant-ptr (:pointer :void))

(cffi:defctype %gdextension::initialization-function (:pointer :void))

(cffi:defctype %gdextension::int :long-long)

(cffi:defctype %gdextension::interface-array-operator-index (:pointer :void))

(cffi:defctype %gdextension::interface-array-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-array-ref (:pointer :void))

(cffi:defctype %gdextension::interface-array-set-typed (:pointer :void))

(cffi:defctype %gdextension::interface-callable-custom-create (:pointer :void))

(cffi:defctype %gdextension::interface-callable-custom-create2 (:pointer :void))

(cffi:defctype %gdextension::interface-callable-custom-get-user-data
               (:pointer :void))

(cffi:defctype %gdextension::interface-classdb-construct-object
               (:pointer :void))

(cffi:defctype %gdextension::interface-classdb-construct-object2
               (:pointer :void))

(cffi:defctype %gdextension::interface-classdb-get-class-tag (:pointer :void))

(cffi:defctype %gdextension::interface-classdb-get-method-bind (:pointer :void))

(cffi:defctype %gdextension::interface-classdb-register-extension-class
               (:pointer :void))

(cffi:defctype %gdextension::interface-classdb-register-extension-class2
               (:pointer :void))

(cffi:defctype %gdextension::interface-classdb-register-extension-class3
               (:pointer :void))

(cffi:defctype %gdextension::interface-classdb-register-extension-class4
               (:pointer :void))

(cffi:defctype
 %gdextension::interface-classdb-register-extension-class-integer-constant
 (:pointer :void))

(cffi:defctype %gdextension::interface-classdb-register-extension-class-method
               (:pointer :void))

(cffi:defctype
 %gdextension::interface-classdb-register-extension-class-property
 (:pointer :void))

(cffi:defctype
 %gdextension::interface-classdb-register-extension-class-property-group
 (:pointer :void))

(cffi:defctype
 %gdextension::interface-classdb-register-extension-class-property-indexed
 (:pointer :void))

(cffi:defctype
 %gdextension::interface-classdb-register-extension-class-property-subgroup
 (:pointer :void))

(cffi:defctype %gdextension::interface-classdb-register-extension-class-signal
               (:pointer :void))

(cffi:defctype
 %gdextension::interface-classdb-register-extension-class-virtual-method
 (:pointer :void))

(cffi:defctype %gdextension::interface-classdb-unregister-extension-class
               (:pointer :void))

(cffi:defctype %gdextension::interface-dictionary-operator-index
               (:pointer :void))

(cffi:defctype %gdextension::interface-dictionary-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-dictionary-set-typed (:pointer :void))

(cffi:defctype %gdextension::interface-editor-add-plugin (:pointer :void))

(cffi:defctype %gdextension::interface-editor-remove-plugin (:pointer :void))

(cffi:defctype %gdextension::interface-file-access-get-buffer (:pointer :void))

(cffi:defctype %gdextension::interface-file-access-store-buffer
               (:pointer :void))

(cffi:defctype %gdextension::interface-get-godot-version (:pointer :void))

(cffi:defctype %gdextension::interface-get-library-path (:pointer :void))

(cffi:defctype %gdextension::interface-get-native-struct-size (:pointer :void))

(cffi:defctype %gdextension::interface-get-proc-address (:pointer :void))

(cffi:defctype %gdextension::interface-get-variant-from-type-constructor
               (:pointer :void))

(cffi:defctype %gdextension::interface-get-variant-get-internal-ptr-func
               (:pointer :void))

(cffi:defctype %gdextension::interface-get-variant-to-type-constructor
               (:pointer :void))

(cffi:defctype %gdextension::interface-global-get-singleton (:pointer :void))

(cffi:defctype %gdextension::interface-image-ptr (:pointer :void))

(cffi:defctype %gdextension::interface-image-ptrw (:pointer :void))

(cffi:defctype %gdextension::interface-mem-alloc (:pointer :void))

(cffi:defctype %gdextension::interface-mem-free (:pointer :void))

(cffi:defctype %gdextension::interface-mem-realloc (:pointer :void))

(cffi:defctype %gdextension::interface-object-call-script-method
               (:pointer :void))

(cffi:defctype %gdextension::interface-object-cast-to (:pointer :void))

(cffi:defctype %gdextension::interface-object-destroy (:pointer :void))

(cffi:defctype %gdextension::interface-object-free-instance-binding
               (:pointer :void))

(cffi:defctype %gdextension::interface-object-get-class-name (:pointer :void))

(cffi:defctype %gdextension::interface-object-get-instance-binding
               (:pointer :void))

(cffi:defctype %gdextension::interface-object-get-instance-from-id
               (:pointer :void))

(cffi:defctype %gdextension::interface-object-get-instance-id (:pointer :void))

(cffi:defctype %gdextension::interface-object-get-script-instance
               (:pointer :void))

(cffi:defctype %gdextension::interface-object-has-script-method
               (:pointer :void))

(cffi:defctype %gdextension::interface-object-method-bind-call (:pointer :void))

(cffi:defctype %gdextension::interface-object-method-bind-ptrcall
               (:pointer :void))

(cffi:defctype %gdextension::interface-object-set-instance (:pointer :void))

(cffi:defctype %gdextension::interface-object-set-instance-binding
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-byte-array-operator-index
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-byte-array-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-color-array-operator-index
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-color-array-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-float32array-operator-index
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-float32array-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-float64array-operator-index
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-float64array-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-int32array-operator-index
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-int32array-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-int64array-operator-index
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-int64array-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-string-array-operator-index
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-string-array-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-vector2array-operator-index
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-vector2array-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-vector3array-operator-index
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-vector3array-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-vector4array-operator-index
               (:pointer :void))

(cffi:defctype %gdextension::interface-packed-vector4array-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-place-holder-script-instance-create
               (:pointer :void))

(cffi:defctype %gdextension::interface-place-holder-script-instance-update
               (:pointer :void))

(cffi:defctype %gdextension::interface-print-error (:pointer :void))

(cffi:defctype %gdextension::interface-print-error-with-message
               (:pointer :void))

(cffi:defctype %gdextension::interface-print-script-error (:pointer :void))

(cffi:defctype %gdextension::interface-print-script-error-with-message
               (:pointer :void))

(cffi:defctype %gdextension::interface-print-warning (:pointer :void))

(cffi:defctype %gdextension::interface-print-warning-with-message
               (:pointer :void))

(cffi:defctype %gdextension::interface-ref-get-object (:pointer :void))

(cffi:defctype %gdextension::interface-ref-set-object (:pointer :void))

(cffi:defctype %gdextension::interface-script-instance-create (:pointer :void))

(cffi:defctype %gdextension::interface-script-instance-create2 (:pointer :void))

(cffi:defctype %gdextension::interface-script-instance-create3 (:pointer :void))

(cffi:defctype %gdextension::interface-string-name-new-with-latin1chars
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-name-new-with-utf8chars
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-name-new-with-utf8chars-and-len
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-new-with-latin1chars
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-new-with-latin1chars-and-len
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-new-with-utf16chars
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-new-with-utf16chars-and-len
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-new-with-utf16chars-and-len2
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-new-with-utf32chars
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-new-with-utf32chars-and-len
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-new-with-utf8chars
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-new-with-utf8chars-and-len
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-new-with-utf8chars-and-len2
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-new-with-wide-chars
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-new-with-wide-chars-and-len
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-operator-index (:pointer :void))

(cffi:defctype %gdextension::interface-string-operator-index-const
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-operator-plus-eq-c32str
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-operator-plus-eq-char
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-operator-plus-eq-cstr
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-operator-plus-eq-string
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-operator-plus-eq-wcstr
               (:pointer :void))

(cffi:defctype %gdextension::interface-string-resize (:pointer :void))

(cffi:defctype %gdextension::interface-string-to-latin1chars (:pointer :void))

(cffi:defctype %gdextension::interface-string-to-utf16chars (:pointer :void))

(cffi:defctype %gdextension::interface-string-to-utf32chars (:pointer :void))

(cffi:defctype %gdextension::interface-string-to-utf8chars (:pointer :void))

(cffi:defctype %gdextension::interface-string-to-wide-chars (:pointer :void))

(cffi:defctype %gdextension::interface-variant-booleanize (:pointer :void))

(cffi:defctype %gdextension::interface-variant-call (:pointer :void))

(cffi:defctype %gdextension::interface-variant-call-static (:pointer :void))

(cffi:defctype %gdextension::interface-variant-can-convert (:pointer :void))

(cffi:defctype %gdextension::interface-variant-can-convert-strict
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-construct (:pointer :void))

(cffi:defctype %gdextension::interface-variant-destroy (:pointer :void))

(cffi:defctype %gdextension::interface-variant-duplicate (:pointer :void))

(cffi:defctype %gdextension::interface-variant-evaluate (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-constant-value
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-indexed (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-keyed (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-named (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-object-instance-id
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-ptr-builtin-method
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-ptr-constructor
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-ptr-destructor
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-ptr-getter (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-ptr-indexed-getter
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-ptr-indexed-setter
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-ptr-keyed-checker
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-ptr-keyed-getter
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-ptr-keyed-setter
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-ptr-operator-evaluator
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-ptr-setter (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-ptr-utility-function
               (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-type (:pointer :void))

(cffi:defctype %gdextension::interface-variant-get-type-name (:pointer :void))

(cffi:defctype %gdextension::interface-variant-has-key (:pointer :void))

(cffi:defctype %gdextension::interface-variant-has-member (:pointer :void))

(cffi:defctype %gdextension::interface-variant-has-method (:pointer :void))

(cffi:defctype %gdextension::interface-variant-hash (:pointer :void))

(cffi:defctype %gdextension::interface-variant-hash-compare (:pointer :void))

(cffi:defctype %gdextension::interface-variant-iter-get (:pointer :void))

(cffi:defctype %gdextension::interface-variant-iter-init (:pointer :void))

(cffi:defctype %gdextension::interface-variant-iter-next (:pointer :void))

(cffi:defctype %gdextension::interface-variant-new-copy (:pointer :void))

(cffi:defctype %gdextension::interface-variant-new-nil (:pointer :void))

(cffi:defctype %gdextension::interface-variant-recursive-hash (:pointer :void))

(cffi:defctype %gdextension::interface-variant-set (:pointer :void))

(cffi:defctype %gdextension::interface-variant-set-indexed (:pointer :void))

(cffi:defctype %gdextension::interface-variant-set-keyed (:pointer :void))

(cffi:defctype %gdextension::interface-variant-set-named (:pointer :void))

(cffi:defctype %gdextension::interface-variant-stringify (:pointer :void))

(cffi:defctype %gdextension::interface-worker-thread-pool-add-native-group-task
               (:pointer :void))

(cffi:defctype %gdextension::interface-worker-thread-pool-add-native-task
               (:pointer :void))

(cffi:defctype %gdextension::interface-xml-parser-open-buffer (:pointer :void))

(cffi:defctype %gdextension::method-bind-ptr (:pointer :void))

(cffi:defctype %gdextension::object-ptr (:pointer :void))

(cffi:defctype %gdextension::ptr-built-in-method (:pointer :void))

(cffi:defctype %gdextension::ptr-constructor (:pointer :void))

(cffi:defctype %gdextension::ptr-destructor (:pointer :void))

(cffi:defctype %gdextension::ptr-getter (:pointer :void))

(cffi:defctype %gdextension::ptr-indexed-getter (:pointer :void))

(cffi:defctype %gdextension::ptr-indexed-setter (:pointer :void))

(cffi:defctype %gdextension::ptr-keyed-checker (:pointer :void))

(cffi:defctype %gdextension::ptr-keyed-getter (:pointer :void))

(cffi:defctype %gdextension::ptr-keyed-setter (:pointer :void))

(cffi:defctype %gdextension::ptr-operator-evaluator (:pointer :void))

(cffi:defctype %gdextension::ptr-setter (:pointer :void))

(cffi:defctype %gdextension::ptr-utility-function (:pointer :void))

(cffi:defctype %gdextension::ref-ptr (:pointer :void))

(cffi:defctype %gdextension::script-instance-data-ptr (:pointer :void))

(cffi:defctype %gdextension::script-instance-property-state-add
               (:pointer :void))

(cffi:defctype %gdextension::script-instance-ptr (:pointer :void))

(cffi:defctype %gdextension::script-language-ptr (:pointer :void))

(cffi:defctype %gdextension::type-from-variant-constructor-func
               (:pointer :void))

(cffi:defctype %gdextension::type-ptr (:pointer :void))

(cffi:defctype %gdextension::uninitialized-object-ptr (:pointer :void))

(cffi:defctype %gdextension::uninitialized-string-name-ptr (:pointer :void))

(cffi:defctype %gdextension::uninitialized-string-ptr (:pointer :void))

(cffi:defctype %gdextension::uninitialized-type-ptr (:pointer :void))

(cffi:defctype %gdextension::uninitialized-variant-ptr (:pointer :void))

(cffi:defctype %gdextension::variant-from-type-constructor-func
               (:pointer :void))

(cffi:defctype %gdextension::variant-get-internal-ptr-func (:pointer :void))

(cffi:defctype %gdextension::s-interface-editor-help-load-xml-from-utf8chars
               (:pointer :void))

(cffi:defctype
 %gdextension::s-interface-editor-help-load-xml-from-utf8chars-and-len
 (:pointer :void))

(eval-when (:load-toplevel :compile-toplevel :execute)
  (export '%gdextension::get-rid-func :%gdextension)
  (export '%gdextension::arguments :%gdextension)
  (export '%gdextension::class-reference :%gdextension)
  (export '%gdextension::error-arg :%gdextension)
  (export '%gdextension::interface-packed-byte-array-operator-index
          :%gdextension)
  (export '%gdextension::get-script-func :%gdextension)
  (export '%gdextension::interface-variant-call :%gdextension)
  (export '%gdextension::interface-variant-duplicate :%gdextension)
  (export '%gdextension::interface-mem-free :%gdextension)
  (export '%gdextension::callable-custom-info2 :%gdextension)
  (export '%gdextension::interface-variant-iter-next :%gdextension)
  (export '%gdextension::script-instance-ref-count-incremented :%gdextension)
  (export '%gdextension::get-argument-count-func :%gdextension)
  (export '%gdextension::int :%gdextension)
  (export '%gdextension::reference-func :%gdextension)
  (export '%gdextension::interface-classdb-get-method-bind :%gdextension)
  (export '%gdextension::const-type-ptr :%gdextension)
  (export '%gdextension::arguments-info :%gdextension)
  (export '%gdextension::class-recreate-instance :%gdextension)
  (export '%gdextension::interface-packed-float64array-operator-index-const
          :%gdextension)
  (export '%gdextension::interface-string-new-with-wide-chars :%gdextension)
  (export '%gdextension::ptr-setter :%gdextension)
  (export '%gdextension::interface-variant-can-convert :%gdextension)
  (export '%gdextension::script-instance-info-struct
          :%gdextension)
  (export '%gdextension::class-get :%gdextension)
  (export '%gdextension::script-instance-info3-struct
          :%gdextension)
  (export '%gdextension::interface-object-call-script-method :%gdextension)
  (export '%gdextension::interface-packed-vector4array-operator-index-const
          :%gdextension)
  (export '%gdextension::callable-custom-to-string :%gdextension)
  (export '%gdextension::class-free-instance :%gdextension)
  (export '%gdextension::free-func :%gdextension)
  (export '%gdextension::instance-binding-callbacks :%gdextension)
  (export '%gdextension::type-from-variant-constructor-func :%gdextension)
  (export '%gdextension::callable-custom-info :%gdextension)
  (export '%gdextension::interface-variant-get-ptr-keyed-setter :%gdextension)
  (export '%gdextension::interface-variant-get-ptr-destructor :%gdextension)
  (export '%gdextension::interface-classdb-register-extension-class-signal
          :%gdextension)
  (export '%gdextension::script-instance-is-placeholder :%gdextension)
  (export '%gdextension::interface-classdb-register-extension-class4
          :%gdextension)
  (export '%gdextension::interface-classdb-get-class-tag :%gdextension)
  (export '%gdextension::has-method-func :%gdextension)
  (export '%gdextension::interface-packed-float64array-operator-index
          :%gdextension)
  (export '%gdextension::interface-print-error-with-message :%gdextension)
  (export '%gdextension::interface-get-library-path :%gdextension)
  (export '%gdextension::instance-binding-callbacks-struct
          :%gdextension)
  (export '%gdextension::create-callback :%gdextension)
  (export '%gdextension::get-fallback-func :%gdextension)
  (export '%gdextension::default-argument-count :%gdextension)
  (export '%gdextension::+interface-h+ :%gdextension)
  (export '%gdextension::class-name :%gdextension)
  (export '%gdextension::ptr-getter :%gdextension)
  (export '%gdextension::is-abstract :%gdextension)
  (export '%gdextension::interface-image-ptr :%gdextension)
  (export '%gdextension::ptr-built-in-method :%gdextension)
  (export '%gdextension::ptr-keyed-checker :%gdextension)
  (export '%gdextension::script-instance-get-property-list :%gdextension)
  (export '%gdextension::object-id :%gdextension)
  (export '%gdextension::class-creation-info4-struct
          :%gdextension)
  (export '%gdextension::call-virtual-with-data-func :%gdextension)
  (export '%gdextension::interface-global-get-singleton :%gdextension)
  (export '%gdextension::class-get-virtual2 :%gdextension)
  (export '%gdextension::script-instance-data-ptr :%gdextension)
  (export '%gdextension::script-instance-info3 :%gdextension)
  (export '%gdextension::class-validate-property :%gdextension)
  (export '%gdextension::class-userdata :%gdextension)
  (export '%gdextension::interface-string-operator-plus-eq-c32str
          :%gdextension)
  (export '%gdextension::refcount-incremented-func :%gdextension)
  (export '%gdextension::interface-packed-int64array-operator-index
          :%gdextension)
  (export '%gdextension::interface-classdb-register-extension-class
          :%gdextension)
  (export '%gdextension::class-creation-info3 :%gdextension)
  (export '%gdextension::interface-variant-get-ptr-constructor :%gdextension)
  (export '%gdextension::script-instance-get :%gdextension)
  (export '%gdextension::get-language-func :%gdextension)
  (export '%gdextension::interface-variant-stringify :%gdextension)
  (export '%gdextension::interface-variant-get-keyed :%gdextension)
  (export '%gdextension::script-instance-free :%gdextension)
  (export '%gdextension::class-method-info-struct :%gdextension)
  (export '%gdextension::interface-mem-realloc :%gdextension)
  (export '%gdextension::string-ptr :%gdextension)
  (export
   '%gdextension::interface-classdb-register-extension-class-property-group
   :%gdextension)
  (export '%gdextension::script-instance-notification :%gdextension)
  (export '%gdextension::callable-custom-free :%gdextension)
  (export '%gdextension::script-language-ptr :%gdextension)
  (export '%gdextension::interface-variant-get-ptr-operator-evaluator
          :%gdextension)
  (export '%gdextension::interface-script-instance-create :%gdextension)
  (export '%gdextension::interface-print-warning-with-message :%gdextension)
  (export '%gdextension::interface-variant-get-named :%gdextension)
  (export '%gdextension::interface-packed-vector2array-operator-index
          :%gdextension)
  (export '%gdextension::interface-packed-vector4array-operator-index
          :%gdextension)
  (export '%gdextension::callable-custom-info-struct
          :%gdextension)
  (export '%gdextension::uninitialized-object-ptr :%gdextension)
  (export '%gdextension::interface-string-operator-plus-eq-char :%gdextension)
  (export '%gdextension::return-value-info :%gdextension)
  (export '%gdextension::interface-editor-remove-plugin :%gdextension)
  (export '%gdextension::script-instance-info :%gdextension)
  (export '%gdextension::interface-packed-int64array-operator-index-const
          :%gdextension)
  (export '%gdextension::instance-binding-reference-callback :%gdextension)
  (export
   '%gdextension::interface-classdb-register-extension-class-integer-constant
   :%gdextension)
  (export '%gdextension::initialization :%gdextension)
  (export '%gdextension::interface-get-variant-from-type-constructor
          :%gdextension)
  (export '%gdextension::notification-func :%gdextension)
  (export '%gdextension::interface-packed-float32array-operator-index
          :%gdextension)
  (export '%gdextension::interface-script-instance-create3 :%gdextension)
  (export '%gdextension::free-callback :%gdextension)
  (export '%gdextension::ptr-utility-function :%gdextension)
  (export '%gdextension::class-creation-info3-struct
          :%gdextension)
  (export '%gdextension::recreate-instance-func :%gdextension)
  (export '%gdextension::interface-ref-get-object :%gdextension)
  (export '%gdextension::interface-variant-get-ptr-builtin-method
          :%gdextension)
  (export '%gdextension::interface-string-to-utf16chars :%gdextension)
  (export '%gdextension::interface-get-proc-address :%gdextension)
  (export '%gdextension::interface-string-operator-plus-eq-cstr :%gdextension)
  (export '%gdextension::is-virtual :%gdextension)
  (export '%gdextension::interface-classdb-register-extension-class-property
          :%gdextension)
  (export '%gdextension::get-method-argument-count-func :%gdextension)
  (export '%gdextension::script-instance-get-script :%gdextension)
  (export '%gdextension::name :%gdextension)
  (export '%gdextension::get-owner-func :%gdextension)
  (export '%gdextension::initialization-level :%gdextension)
  (export '%gdextension::callable-custom-hash :%gdextension)
  (export '%gdextension::script-instance-property-get-revert :%gdextension)
  (export '%gdextension::ptr-operator-evaluator :%gdextension)
  (export '%gdextension::interface-variant-has-member :%gdextension)
  (export '%gdextension::interface-variant-get-indexed :%gdextension)
  (export '%gdextension::ref-ptr :%gdextension)
  (export '%gdextension::script-instance-to-string :%gdextension)
  (export '%gdextension::deinitialize :%gdextension)
  (export '%gdextension::uninitialized-string-name-ptr :%gdextension)
  (export '%gdextension::interface-array-operator-index :%gdextension)
  (export '%gdextension::call-error-struct :%gdextension)
  (export '%gdextension::interface-classdb-unregister-extension-class
          :%gdextension)
  (export '%gdextension::script-instance-validate-property :%gdextension)
  (export '%gdextension::script-instance-get-class-category :%gdextension)
  (export '%gdextension::script-instance-info2-struct
          :%gdextension)
  (export '%gdextension::interface-classdb-construct-object2 :%gdextension)
  (export '%gdextension::interface-object-get-script-instance :%gdextension)
  (export '%gdextension::callable-custom-get-argument-count :%gdextension)
  (export
   '%gdextension::interface-classdb-register-extension-class-property-subgroup
   :%gdextension)
  (export '%gdextension::interface-object-method-bind-ptrcall :%gdextension)
  (export '%gdextension::get-property-type-func :%gdextension)
  (export '%gdextension::interface-packed-string-array-operator-index-const
          :%gdextension)
  (export '%gdextension::type-ptr :%gdextension)
  (export '%gdextension::script-instance-property-state-add :%gdextension)
  (export '%gdextension::interface-print-script-error-with-message
          :%gdextension)
  (export '%gdextension::script-instance-property-can-revert :%gdextension)
  (export '%gdextension::validate-property-func :%gdextension)
  (export '%gdextension::method-userdata :%gdextension)
  (export '%gdextension::major :%gdextension)
  (export '%gdextension::class-unreference :%gdextension)
  (export '%gdextension::callable-custom-call :%gdextension)
  (export '%gdextension::interface-string-new-with-wide-chars-and-len
          :%gdextension)
  (export '%gdextension::expected :%gdextension)
  (export '%gdextension::variant-ptr :%gdextension)
  (export '%gdextension::call-error-type :%gdextension)
  (export '%gdextension::ptr-indexed-getter :%gdextension)
  (export '%gdextension::interface-object-set-instance-binding :%gdextension)
  (export '%gdextension::unreference-func :%gdextension)
  (export '%gdextension::interface-get-variant-to-type-constructor
          :%gdextension)
  (export '%gdextension::variant-operator :%gdextension)
  (export '%gdextension::class-creation-info :%gdextension)
  (export '%gdextension::script-instance-ptr :%gdextension)
  (export '%gdextension::interface-variant-set-keyed :%gdextension)
  (export '%gdextension::interface-get-native-struct-size :%gdextension)
  (export '%gdextension::class-library-ptr :%gdextension)
  (export '%gdextension::get-method-list-func :%gdextension)
  (export '%gdextension::class-virtual-method-info :%gdextension)
  (export '%gdextension::class-method-flags-enum :%gdextension)
  (export '%gdextension::interface-variant-has-key :%gdextension)
  (export '%gdextension::class-get-virtual-call-data :%gdextension)
  (export '%gdextension::has-return-value :%gdextension)
  (export '%gdextension::interface-object-has-script-method :%gdextension)
  (export '%gdextension::interface-string-operator-index-const :%gdextension)
  (export '%gdextension::interface-string-new-with-utf32chars :%gdextension)
  (export '%gdextension::get-virtual-func :%gdextension)
  (export '%gdextension::s-interface-editor-help-load-xml-from-utf8chars
          :%gdextension)
  (export '%gdextension::callable-custom-less-than :%gdextension)
  (export '%gdextension::interface-variant-get-type :%gdextension)
  (export '%gdextension::interface-packed-byte-array-operator-index-const
          :%gdextension)
  (export '%gdextension::interface-packed-vector2array-operator-index-const
          :%gdextension)
  (export '%gdextension::bool :%gdextension)
  (export '%gdextension::interface-classdb-construct-object :%gdextension)
  (export '%gdextension::class-property-can-revert :%gdextension)
  (export '%gdextension::ptr-indexed-setter :%gdextension)
  (export '%gdextension::interface-variant-hash-compare :%gdextension)
  (export '%gdextension::return-value :%gdextension)
  (export '%gdextension::interface-script-instance-create2 :%gdextension)
  (export '%gdextension::interface-object-get-instance-id :%gdextension)
  (export '%gdextension::is-placeholder-func :%gdextension)
  (export '%gdextension::interface-mem-alloc :%gdextension)
  (export '%gdextension::script-instance-get-property-type :%gdextension)
  (export '%gdextension::interface-variant-get-type-name :%gdextension)
  (export '%gdextension::interface-variant-get-constant-value :%gdextension)
  (export '%gdextension::get-virtual-call-data-func :%gdextension)
  (export '%gdextension::callable-userdata :%gdextension)
  (export '%gdextension::class-creation-info2 :%gdextension)
  (export '%gdextension::callable-custom-is-valid :%gdextension)
  (export '%gdextension::property-get-revert-func :%gdextension)
  (export '%gdextension::interface-object-get-instance-from-id :%gdextension)
  (export '%gdextension::interface-dictionary-operator-index-const
          :%gdextension)
  (export '%gdextension::script-instance-get-method-argument-count
          :%gdextension)
  (export '%gdextension::interface-string-resize :%gdextension)
  (export '%gdextension::interface-variant-new-nil :%gdextension)
  (export '%gdextension::interface-callable-custom-get-user-data :%gdextension)
  (export '%gdextension::interface-callable-custom-create2 :%gdextension)
  (export '%gdextension::interface-xml-parser-open-buffer :%gdextension)
  (export '%gdextension::userdata :%gdextension)
  (export '%gdextension::const-ref-ptr :%gdextension)
  (export '%gdextension::interface-variant-iter-init :%gdextension)
  (export '%gdextension::argument-count :%gdextension)
  (export '%gdextension::interface-packed-int32array-operator-index
          :%gdextension)
  (export '%gdextension::script-instance-notification2 :%gdextension)
  (export '%gdextension::class-virtual-method-info-struct
          :%gdextension)
  (export '%gdextension::class-get-virtual :%gdextension)
  (export '%gdextension::interface-string-new-with-latin1chars :%gdextension)
  (export '%gdextension::property-can-revert-func :%gdextension)
  (export '%gdextension::get-func :%gdextension)
  (export '%gdextension::object-ptr :%gdextension)
  (export '%gdextension::class-create-instance2 :%gdextension)
  (export '%gdextension::interface-image-ptrw :%gdextension)
  (export '%gdextension::script-instance-free-method-list :%gdextension)
  (export '%gdextension::interface-classdb-register-extension-class-method
          :%gdextension)
  (export '%gdextension::instance-binding-free-callback :%gdextension)
  (export '%gdextension::interface-packed-vector3array-operator-index-const
          :%gdextension)
  (export '%gdextension::interface-string-name-new-with-utf8chars-and-len
          :%gdextension)
  (export '%gdextension::set-func :%gdextension)
  (export '%gdextension::interface-string-name-new-with-latin1chars
          :%gdextension)
  (export '%gdextension::class-method-info :%gdextension)
  (export '%gdextension::less-than-func :%gdextension)
  (export '%gdextension::to-string-func :%gdextension)
  (export '%gdextension::interface-string-new-with-utf32chars-and-len
          :%gdextension)
  (export '%gdextension::interface-callable-custom-create :%gdextension)
  (export '%gdextension::hint :%gdextension)
  (export '%gdextension::get-property-list-func :%gdextension)
  (export '%gdextension::free-instance-func :%gdextension)
  (export '%gdextension::interface-object-get-instance-binding :%gdextension)
  (export '%gdextension::script-instance-free-property-list2 :%gdextension)
  (export '%gdextension::ptr-keyed-getter :%gdextension)
  (export '%gdextension::is-runtime :%gdextension)
  (export '%gdextension::interface-variant-get-ptr-keyed-checker :%gdextension)
  (export '%gdextension::class-to-string :%gdextension)
  (export '%gdextension::interface-variant-can-convert-strict :%gdextension)
  (export '%gdextension::script-instance-info2 :%gdextension)
  (export '%gdextension::const-string-name-ptr :%gdextension)
  (export '%gdextension::argument :%gdextension)
  (export
   '%gdextension::s-interface-editor-help-load-xml-from-utf8chars-and-len
   :%gdextension)
  (export '%gdextension::interface-variant-get-ptr-setter :%gdextension)
  (export '%gdextension::minimum-initialization-level :%gdextension)
  (export '%gdextension::int32-t :%gdextension)
  (export '%gdextension::string-name-ptr :%gdextension)
  (export '%gdextension::interface-variant-get-ptr-indexed-setter
          :%gdextension)
  (export '%gdextension::interface-dictionary-operator-index :%gdextension)
  (export '%gdextension::interface-array-operator-index-const :%gdextension)
  (export '%gdextension::property-info-struct :%gdextension)
  (export '%gdextension::interface-variant-set-indexed :%gdextension)
  (export '%gdextension::equal-func :%gdextension)
  (export '%gdextension::uninitialized-variant-ptr :%gdextension)
  (export '%gdextension::interface-array-set-typed :%gdextension)
  (export '%gdextension::class-method-validated-call :%gdextension)
  (export '%gdextension::create-instance-func :%gdextension)
  (export '%gdextension::call-func :%gdextension)
  (export '%gdextension::set-fallback-func :%gdextension)
  (export '%gdextension::token :%gdextension)
  (export '%gdextension::interface-ref-set-object :%gdextension)
  (export '%gdextension::class-create-instance :%gdextension)
  (export '%gdextension::class-set :%gdextension)
  (export '%gdextension::id :%gdextension)
  (export '%gdextension::interface-object-get-class-name :%gdextension)
  (export '%gdextension::interface-variant-hash :%gdextension)
  (export '%gdextension::callable-custom-equal :%gdextension)
  (export '%gdextension::interface-variant-call-static :%gdextension)
  (export '%gdextension::interface-string-to-latin1chars :%gdextension)
  (export '%gdextension::interface-packed-float32array-operator-index-const
          :%gdextension)
  (export '%gdextension::gd-object-instance-id :%gdextension)
  (export '%gdextension::is-exposed :%gdextension)
  (export '%gdextension::interface-packed-color-array-operator-index
          :%gdextension)
  (export '%gdextension::call-error-type-enum :%gdextension)
  (export '%gdextension::interface-object-destroy :%gdextension)
  (export '%gdextension::class-get-rid :%gdextension)
  (export
   '%gdextension::interface-classdb-register-extension-class-virtual-method
   :%gdextension)
  (export '%gdextension::variant-get-internal-ptr-func :%gdextension)
  (export '%gdextension::const-variant-ptr :%gdextension)
  (export '%gdextension::interface-get-godot-version :%gdextension)
  (export '%gdextension::script-instance-free-property-list :%gdextension)
  (export '%gdextension::interface-variant-booleanize :%gdextension)
  (export '%gdextension::is-valid-func :%gdextension)
  (export '%gdextension::interface-editor-add-plugin :%gdextension)
  (export '%gdextension::hint-string :%gdextension)
  (export '%gdextension::variant-from-type-constructor-func :%gdextension)
  (export '%gdextension::interface-array-ref :%gdextension)
  (export '%gdextension::class-notification2 :%gdextension)
  (export '%gdextension::interface-object-cast-to :%gdextension)
  (export '%gdextension::interface-file-access-store-buffer :%gdextension)
  (export '%gdextension::interface-string-to-utf32chars :%gdextension)
  (export '%gdextension::class-creation-info4 :%gdextension)
  (export '%gdextension::interface-variant-recursive-hash :%gdextension)
  (export '%gdextension::instance-binding-create-callback :%gdextension)
  (export '%gdextension::interface-object-method-bind-call :%gdextension)
  (export '%gdextension::interface-string-new-with-utf8chars-and-len
          :%gdextension)
  (export '%gdextension::script-instance-free-method-list2 :%gdextension)
  (export '%gdextension::class-method-call :%gdextension)
  (export '%gdextension::class-free-property-list2 :%gdextension)
  (export '%gdextension::interface-variant-get-ptr-getter :%gdextension)
  (export '%gdextension::default-arguments :%gdextension)
  (export '%gdextension::class-method-flags :%gdextension)
  (export '%gdextension::interface-variant-get-object-instance-id
          :%gdextension)
  (export '%gdextension::godot-version :%gdextension)
  (export '%gdextension::script-instance-get-language :%gdextension)
  (export '%gdextension::variant-type-enum :%gdextension)
  (export '%gdextension::interface-variant-construct :%gdextension)
  (export '%gdextension::script-instance-get-property-state :%gdextension)
  (export '%gdextension::hash-func :%gdextension)
  (export '%gdextension::interface-classdb-register-extension-class3
          :%gdextension)
  (export '%gdextension::class-get-property-list :%gdextension)
  (export '%gdextension::initialization-level-enum
          :%gdextension)
  (export '%gdextension::reference-callback :%gdextension)
  (export '%gdextension::initialize :%gdextension)
  (export '%gdextension::interface-classdb-register-extension-class2
          :%gdextension)
  (export '%gdextension::interface-place-holder-script-instance-create
          :%gdextension)
  (export '%gdextension::interface-place-holder-script-instance-update
          :%gdextension)
  (export '%gdextension::variant-operator-enum :%gdextension)
  (export '%gdextension::const-string-ptr :%gdextension)
  (export '%gdextension::script-instance-ref-count-decremented :%gdextension)
  (export '%gdextension::minor :%gdextension)
  (export '%gdextension::call-error :%gdextension)
  (export '%gdextension::class-instance-ptr :%gdextension)
  (export '%gdextension::class-method-ptr-call :%gdextension)
  (export '%gdextension::icon-path :%gdextension)
  (export '%gdextension::interface-worker-thread-pool-add-native-task
          :%gdextension)
  (export '%gdextension::class-method-argument-metadata-enum
          :%gdextension)
  (export '%gdextension::ptr-keyed-setter :%gdextension)
  (export '%gdextension::interface-variant-get-ptr-indexed-getter
          :%gdextension)
  (export '%gdextension::variant-type :%gdextension)
  (export '%gdextension::interface-variant-set-named :%gdextension)
  (export '%gdextension::return-value-metadata :%gdextension)
  (export
   '%gdextension::interface-classdb-register-extension-class-property-indexed
   :%gdextension)
  (export '%gdextension::interface-variant-evaluate :%gdextension)
  (export '%gdextension::usage :%gdextension)
  (export '%gdextension::interface-dictionary-set-typed :%gdextension)
  (export '%gdextension::class-creation-info2-struct
          :%gdextension)
  (export '%gdextension::class-property-get-revert :%gdextension)
  (export '%gdextension::class-method-argument-metadata :%gdextension)
  (export '%gdextension::interface-print-warning :%gdextension)
  (export '%gdextension::method-info :%gdextension)
  (export '%gdextension::ptr-constructor :%gdextension)
  (export '%gdextension::ptr-destructor :%gdextension)
  (export '%gdextension::interface-object-free-instance-binding :%gdextension)
  (export '%gdextension::script-instance-has-method :%gdextension)
  (export '%gdextension::refcount-decremented-func :%gdextension)
  (export '%gdextension::class-notification :%gdextension)
  (export '%gdextension::interface-string-new-with-utf8chars :%gdextension)
  (export '%gdextension::interface-variant-set :%gdextension)
  (export '%gdextension::script-instance-call :%gdextension)
  (export '%gdextension::interface-print-error :%gdextension)
  (export '%gdextension::uninitialized-string-ptr :%gdextension)
  (export '%gdextension::flags :%gdextension)
  (export '%gdextension::interface-variant-has-method :%gdextension)
  (export '%gdextension::patch :%gdextension)
  (export '%gdextension::ptrcall-func :%gdextension)
  (export '%gdextension::class-call-virtual :%gdextension)
  (export '%gdextension::interface-string-new-with-utf16chars-and-len2
          :%gdextension)
  (export '%gdextension::interface-string-new-with-utf16chars-and-len
          :%gdextension)
  (export '%gdextension::initialization-function :%gdextension)
  (export '%gdextension::interface-string-operator-index :%gdextension)
  (export '%gdextension::interface-variant-new-copy :%gdextension)
  (export '%gdextension::script-instance-set :%gdextension)
  (export '%gdextension::method-bind-ptr :%gdextension)
  (export '%gdextension::get-property-state-func :%gdextension)
  (export '%gdextension::interface-string-to-wide-chars :%gdextension)
  (export '%gdextension::class-free-property-list :%gdextension)
  (export '%gdextension::script-instance-get-owner :%gdextension)
  (export '%gdextension::interface-packed-string-array-operator-index
          :%gdextension)
  (export '%gdextension::free-method-list-func :%gdextension)
  (export '%gdextension::uint32-t :%gdextension)
  (export '%gdextension::interface-string-new-with-latin1chars-and-len
          :%gdextension)
  (export '%gdextension::interface-packed-int32array-operator-index-const
          :%gdextension)
  (export '%gdextension::interface-variant-iter-get :%gdextension)
  (export '%gdextension::interface-variant-get-ptr-keyed-getter :%gdextension)
  (export '%gdextension::string :%gdextension)
  (export '%gdextension::interface-object-set-instance :%gdextension)
  (export '%gdextension::initialization-struct :%gdextension)
  (export '%gdextension::interface-string-operator-plus-eq-string
          :%gdextension)
  (export '%gdextension::interface-variant-get :%gdextension)
  (export '%gdextension::interface-packed-color-array-operator-index-const
          :%gdextension)
  (export '%gdextension::script-instance-get-method-list :%gdextension)
  (export '%gdextension::get-class-category-func :%gdextension)
  (export '%gdextension::method-flags :%gdextension)
  (export '%gdextension::interface-print-script-error :%gdextension)
  (export '%gdextension::interface-variant-get-ptr-utility-function
          :%gdextension)
  (export '%gdextension::interface-packed-vector3array-operator-index
          :%gdextension)
  (export '%gdextension::interface-variant-destroy :%gdextension)
  (export '%gdextension::const-object-ptr :%gdextension)
  (export '%gdextension::callable-custom-info2-struct
          :%gdextension)
  (export '%gdextension::uninitialized-type-ptr :%gdextension)
  (export '%gdextension::interface-string-to-utf8chars :%gdextension)
  (export '%gdextension::class-creation-info-struct
          :%gdextension)
  (export '%gdextension::interface-file-access-get-buffer :%gdextension)
  (export '%gdextension::type :%gdextension)
  (export '%gdextension::interface-string-operator-plus-eq-wcstr :%gdextension)
  (export '%gdextension::interface-worker-thread-pool-add-native-group-task
          :%gdextension)
  (export '%gdextension::interface-string-new-with-utf8chars-and-len2
          :%gdextension)
  (export '%gdextension::interface-string-name-new-with-utf8chars
          :%gdextension)
  (export '%gdextension::method-info-struct :%gdextension)
  (export '%gdextension::free-property-list-func :%gdextension)
  (export '%gdextension::class-get-virtual-call-data2 :%gdextension)
  (export '%gdextension::godot-version-struct :%gdextension)
  (export '%gdextension::interface-string-new-with-utf16chars :%gdextension)
  (export '%gdextension::arguments-metadata :%gdextension)
  (export '%gdextension::property-info :%gdextension)
  (export '%gdextension::class-call-virtual-with-data :%gdextension)
  (export '%gdextension::interface-get-variant-get-internal-ptr-func
          :%gdextension))

